# Generated by Django 2.2.7 on 2019-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_short_content',
            field=models.TextField(default=4, max_length=300),
            preserve_default=False,
        ),
    ]
