# Generated by Django 2.2.7 on 2019-11-30 18:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191128_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_img_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
