# Generated by Django 2.2.7 on 2019-11-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20191201_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_img_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
