# Generated by Django 2.2.7 on 2019-11-30 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20191201_0138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_img_link',
        ),
    ]
