# Generated by Django 2.2.7 on 2019-12-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
