# Generated by Django 2.2.7 on 2019-12-02 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_car_short_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='img_title',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
