# Generated by Django 2.2.7 on 2019-12-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_car_img_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price',
            field=models.CharField(default=0, max_length=40),
        ),
    ]
