# Generated by Django 2.2.7 on 2019-12-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0002_auto_20191202_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='model',
            field=models.CharField(default='Выберите модель', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='surname',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
