# Generated by Django 2.2.7 on 2019-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0003_auto_20191202_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(default='', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='male',
            field=models.CharField(default='male', max_length=10),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='mark',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='model',
            field=models.CharField(default='Выберите модель', max_length=50),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='phone',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='testdrive',
            name='surname',
            field=models.CharField(default='', max_length=30),
        ),
    ]
