# Generated by Django 2.2.7 on 2019-12-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdrive', '0004_auto_20191202_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testdrive',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
